// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEe1wYe8QL0zzbps5XF_91DibyupHUqsY',
    appId: '1:663647392487:web:9e7f6c9cf513c7ea188842',
    messagingSenderId: '663647392487',
    projectId: 'narrow-gil',
    authDomain: 'narrow-gil.firebaseapp.com',
    storageBucket: 'narrow-gil.firebasestorage.app',
    measurementId: 'G-WJ7P6TVHDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOBb42IL4HDzW9UfWxJh2jSTm5sy0t4jE',
    appId: '1:663647392487:android:16260f3ec54680d6188842',
    messagingSenderId: '663647392487',
    projectId: 'narrow-gil',
    storageBucket: 'narrow-gil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJVn3UpKZS2ytXnqecxGakELedCwXsvqI',
    appId: '1:663647392487:ios:c0ac2f3d142b04a7188842',
    messagingSenderId: '663647392487',
    projectId: 'narrow-gil',
    storageBucket: 'narrow-gil.firebasestorage.app',
    androidClientId: '663647392487-ibfsin9gm0d373i6vgm16ctcif8i4mu3.apps.googleusercontent.com',
    iosClientId: '663647392487-4ratv2qfkdphqobe5mqsvigjgt2kukfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.narrowGil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJVn3UpKZS2ytXnqecxGakELedCwXsvqI',
    appId: '1:663647392487:ios:c0ac2f3d142b04a7188842',
    messagingSenderId: '663647392487',
    projectId: 'narrow-gil',
    storageBucket: 'narrow-gil.firebasestorage.app',
    androidClientId: '663647392487-ibfsin9gm0d373i6vgm16ctcif8i4mu3.apps.googleusercontent.com',
    iosClientId: '663647392487-4ratv2qfkdphqobe5mqsvigjgt2kukfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.narrowGil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEe1wYe8QL0zzbps5XF_91DibyupHUqsY',
    appId: '1:663647392487:web:04886cbd22af4def188842',
    messagingSenderId: '663647392487',
    projectId: 'narrow-gil',
    authDomain: 'narrow-gil.firebaseapp.com',
    storageBucket: 'narrow-gil.firebasestorage.app',
    measurementId: 'G-CYZBDWP7JF',
  );

}